<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1"/>
        <PackageReference Include="xunit.v3" Version="4.0.1"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/Shared.Vocabulary/Shared.Vocabulary.csproj"/>
    </ItemGroup>

</Project>
