<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Dapper" Version="2.1.89" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="11.0.0-rc.1.26425.128" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
        <PackageReference Include="Npgsql" Version="10.0.3" />
        <PackageReference Include="xunit.v3" Version="4.0.1" />
        <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/Access.Api/Access.Api.csproj" />
    </ItemGroup>

</Project>
